### PR TITLE
[factorization] External packages to be optional

### PR DESCRIPTION
**Pull request by mesnardo**
This PR addresses issue #106 .

External packages (yaml-cpp-0.5.1, Boost-1.65.1, gtest-1.7.0, and AmgXWrapper-1.0-beta2) have been removed from the repository.

Checks of header files and libraries are performed at configuration time to detect whether or not a package (that PetIBM depends on) is available and correctly installed.
If the libraries and include files are not in searchable directories, the configure script will warn you.

When the package is already installed on the machine, you can provide the following configuration arguments:
- `--with-petsc-dir=PATH`
- `--with-petsc-arch=NAME`
- `--with-cuda-dir=PATH`
- `--with-amgx-dir=PATH`
- `--with-yamlcpp-dir=PATH`
- `--with-boost-dir=PATH`
- `--with-gtest-dir=PATH`
- `--with-amgxwrapper-dir=PATH`

As it was already the case, we require PETSc to be installed prior building PetIBM.
If you want to use the iterative solvers from AmgX, we require CUDA and AmgX to be installed prior building PetIBM.

In the case where yaml-cpp, Boost, gtest, and/or AmgXWrapper are not installed, we provide support through the configuration to download and installed them with the command-line arguments:
- `--enable-boost` (Boost-1.65.1)
- `--enable-yamlcpp` (yaml-cpp-0.5.1)
- `--enable-gtest` (gtest-1.7.0)
- `--enable-amgxwrapper` (AmgXWrapper-1.1 compatible with AmgX-2.0)

Additionally, with this PR, unused folders in the `tests` directory have been removed and the Travis file updated.

Configuration, compilation, tests, and installation have been checked on Ubuntu-16.04 and OSX-10.12.6.

Assigning @piyueh for review.

### CODE REVIEW

**Comment by piyueh** [comment]
> If the libraries and include files are not in searchable directories, the configure script will warn you.

Should it be a warning or an error if packages are not found in the standard path?

**Comment by piyueh** [comment]
And why is Travis checking this branch? I thought Travis only checks the master branch?

**Comment by mesnardo** [comment]
Sorry, not a warning, but an error message.

**Comment by mesnardo** [comment]
Travis was triggered for all branches.
Now testing only when trying to merge into develop or master branches.

**Comment by piyueh** [comment]
When there are some kinds of typos in `configure` flags, the `configure` only returns warnings instead of errors. Is this an expected behavior of `configure`?

For example, if I intend to use `--with-amgx-dir`, but I type `--with-amgx` instead, there will be no error. `configure` will just give a warning of unrecognized options hidden in the output of `configure` and continue to finish the configuration.

**Comment by mesnardo** [comment]
You can turn this warning into an error with the command-line parameter `--enable-option-checking=fatal`.
You'll get:
```
configure: error: unrecognized options: --with-amgx
```

**Comment by piyueh** [comment]
Regarding AmgX, it seems our `configure` is now specifically for AmgX-2.0 and eliminates the flexibility of using AmgX-1.0 or other kinds of installation structures (For example if users put AmgX libraries and headers in subfolders different than where they are supposed to be under the AmgX installation path.). I just want to confirm this is an intentional design.

Another question is the `configure` only looks for the shared AmgX library (i.e., `libamgxsh.so`) regardless whether users are building static PetIBM library or not. But in AmgX 2.0, it's possible to have, or even only have a static AmgX library, which has the default name `libamgx.a`. Should we consider this possibility in the future? (I think `libamgxsh.so` is good enough for now.)

**Comment by piyueh** [comment]
`configure` failed during building AmgXWrapper with the following flags:
```
$PETIBM_SRC/configure \
    --prefix=$PETIBM_DIR \
    --with-petsc-dir=<petsc installation> \
    --with-amgx-dir=<amgx installation> \
    --with-cuda-dir=<cuda 6.5 installation> \
    --enable-amgxwrapper \
    --disable-shared \
    CC=mpicc \
    CXX=mpicxx
```

The error message:
```
building AmgXWrapper-1.1 (AmgX-2.0)...
make: *** No rule to make target 'all'.  Stop.
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'all'.  Stop.
make: *** No rule to make target 'install'.  Stop.
checking AmgXSolver.hpp usability... no
checking AmgXSolver.hpp presence... no
checking for AmgXSolver.hpp... no
configure: error: Couldn't find AmgXSolver.hpp...
Please use '--with-amgxwrapper-dir=PATH' to provide the directory of the package
or '--enable-amgxwrapper' to download and install AmgXWrapper-1.1 (AmgX-2.0).
```

The version of GNU make is 4.2.1

**Comment by piyueh** [comment]
Issues regarding `lib` and `lib64`. Not just AmgXWrapper, even gtest. 

For example, on Theo, if I install gtest outside PetIBM, the default folder name of gtest libraries is `lib64`, instead of `lib`.

**Comment by piyueh** [comment]
`make` stops when building `petibm-navierstokes`. It complains about not finding `-lAmgXWrapper`. Do we have to add `AMGXWRAPPER_LDFLAGS` to `Makefile.am` under `applications/navierstokes` and `applications/decoupledibpm`?

**Comment by piyueh** [comment]
`-lAmgXWrapper` works now, but flags for AmgX itself is missing.

**Comment by piyueh** [comment]
Works fine without `--disable-shared` flag. With `--disable-shared` flag, AmgX library flag is missing.

**Comment by piyueh** [comment]
**cuSOLVER** on Linux requires OpenMP support, see [here](http://docs.nvidia.com/cuda/cusolver/index.html#link-openmp).

And regarding to static CUDA libraries, I don't think we are able to do that. Static cuBLAS [requires a different header](http://docs.nvidia.com/cuda/cublas/index.html#device-api), `cublas_v2.h`. This means we may need to modify the source code of AmgX, which is not possible.

**Pull request merged**
