### PR TITLE
JOSS submission

### PR DESCRIPTION
**Pull request by mesnardo**
With this pull-request, we would like to have everything ready to submit PetIBM to JOSS:

Changes with this pull-request:

* Add paper for JOSS (`paper.md`, `paper.bib`, and `codemeta.json`),
* Update title for PetIBM (`paper.md`, `README.md`, and `Doxyfile`),
* Update Change Log (with new Travis CI build workflow).

Does @anushkrish have an ORCID id so we can add it to the metadata?

Proposed title:

"PetIBM: toolbox and applications of the immersed-boundary method on distributed-memory architectures"

Proposed keywords:

1. Computational Fluid Dynamics,
2. Immersed-Boundary Method,
3. PETSc,
4. NVIDIA AmgX

Once we merge this PR into `develop`, I will update the version of PetIBM, setup `gh-pages` (to have the Doxygen documentation online), draft the GitHub release, and delete the Wiki pages (not used anymore).

Ping @labarba, @piyueh, and @anushkrish for the review.

### CODE REVIEW

**Comment by piyueh** [comment]
I suggest add **GPU** to keywords.

**Comment by anushkrish** [comment]
Everything looks good to me! I do not have an ORCID. Do you recommend that I get one?

**Comment by mesnardo** [comment]
@anushkrish, that would be good if you get an ORCID id.

**Comment by anushkrish** [comment]
https://orcid.org/0000-0001-6409-7022

**Pull request merged**
